# Generated by Django 3.2.22 on 2023-10-17 03:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section_grades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('SPRING', 'Spring'), ('SUMMER', 'Summer'), ('FALL', 'Fall'), ('WINTER', 'Winter')], max_length=10)),
                ('year', models.PositiveIntegerField()),
                ('subject_code', models.CharField(max_length=4)),
                ('course_code', models.CharField(max_length=4)),
                ('section_code', models.CharField(max_length=4)),
                ('professor_name', models.CharField(max_length=100)),
                ('a_count', models.PositiveIntegerField()),
                ('b_count', models.PositiveIntegerField()),
                ('c_count', models.PositiveIntegerField()),
                ('d_count', models.PositiveIntegerField()),
                ('f_count', models.PositiveIntegerField()),
                ('q_count', models.PositiveIntegerField()),
                ('i_count', models.PositiveIntegerField()),
                ('s_count', models.PositiveIntegerField()),
                ('u_count', models.PositiveIntegerField()),
                ('x_count', models.PositiveIntegerField()),
                ('answers_one', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, size=None)),
                ('answers_two', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, size=None)),
                ('answers_three', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, size=None)),
                ('answers_four', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, size=None)),
                ('answers_five', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, size=None)),
                ('answers_six', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, size=None)),
            ],
        ),
    ]
